<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-07-13T22:05:38 IST" name="Suite" finished-at="2024-07-13T22:06:04 IST" duration-ms="26320">
    <groups>
    </groups>
    <test started-at="2024-07-13T22:05:38 IST" name="Test" finished-at="2024-07-13T22:06:04 IST" duration-ms="26320">
      <class name="api.TC01_Lead">
        <test-method is-config="true" signature="setup()[pri:0, instance:api.TC01_Lead@25ce9dc4]" started-at="2024-07-13T22:05:38 IST" name="setup" finished-at="2024-07-13T22:05:38 IST" duration-ms="336" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testCreateNewLeadResourceByPassingBlankResponse()[pri:0, instance:api.TC01_Lead@25ce9dc4]" started-at="2024-07-13T22:05:38 IST" name="testCreateNewLeadResourceByPassingBlankResponse" finished-at="2024-07-13T22:05:41 IST" duration-ms="3012" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateNewLeadResourceByPassingBlankResponse -->
        <test-method signature="testCreateNewLeadResourceByPassingIncompleteObjects()[pri:0, instance:api.TC01_Lead@25ce9dc4]" started-at="2024-07-13T22:05:41 IST" name="testCreateNewLeadResourceByPassingIncompleteObjects" finished-at="2024-07-13T22:05:58 IST" duration-ms="16889" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [400] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at api.TC01_Lead.testCreateNewLeadResourceByPassingIncompleteObjects(TC01_Lead.java:122)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateNewLeadResourceByPassingIncompleteObjects -->
        <test-method signature="testCreateNewLeadResourceByPassingMandatoryAndOptionalObjects()[pri:0, instance:api.TC01_Lead@25ce9dc4]" started-at="2024-07-13T22:05:58 IST" name="testCreateNewLeadResourceByPassingMandatoryAndOptionalObjects" finished-at="2024-07-13T22:06:04 IST" duration-ms="5984" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateNewLeadResourceByPassingMandatoryAndOptionalObjects -->
      </class> <!-- api.TC01_Lead -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
